{
 "title": "My Cluster Vulnerabilities",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Vulnerabilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"critical\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"high\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"medium\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{severity=\"low\"})",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Evolution",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(namespace_vulnerabilities_total{}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  { "title": "Important", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namespace_vulnerabilities_total{severity=\"critical\"}>0",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Namespaces",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "namespace_vulnerabilities_total{severity=\"critical\"}"
    },
    {
     "expr": "namespace_vulnerabilities_total{severity=\"high\"}"
    },
    {
     "expr": "namespace_vulnerabilities_total{severity=\"medium\"}"
    },
    {
     "expr": "namespace_vulnerabilities_total{severity=\"low\"}"
    }
   ]
  },
  {
   "title": "Images",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "image_vulnerabilities_total{severity=\"critical\"}"
    },
    {
     "expr": "image_vulnerabilities_total{severity=\"high\"}"
    },
    {
     "expr": "image_vulnerabilities_total{severity=\"medium\"}"
    },
    {
     "expr": "image_vulnerabilities_total{severity=\"low\"}"
    }
   ]
  }
 ]
}