# Default values for kciss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kciss:
  replicaCount: 1
  port: 9300
  targetPort: 9300
  interval: 3600
  endpoint: "/kciss-metrics"
  image:
    repository: sokube/kciss
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
  containerSecurityContext:
    runAsUser: 2000
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  serviceAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/kciss-metrics"
  extraContainers: []
  # - image: quay.io/oauth2-proxy/oauth2-proxy
  #   name: oauth-proxy
  #   args:
  #     - '--config=/etc/oauth/oauth.conf'
  #   ports:
  #     - containerPort: 8081
  #       name: proxy
  #   volumeMounts:
  #       - name: sso-oauth-config
  #         mountPath: "/etc/oauth/oauth.conf"
  extraVolumes: []
  # - name: sso-oauth-config
  #   configMap:
  #     defaultMode: 420
  #     name: sso-oauth-config

trivy:
  replicaCount: 1
  port: 8080
  service:
    port: 8080
  serviceAccount:
    create: true
  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534
  securityContext:
    privileged: false
    readOnlyRootFilesystem: true
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

podAnnotations: {}
imagePullSecrets: []

ingress:
  enabled: false
  address: "mycluster.example.com"
